language: ruby
dist: xenial
cache: bundler

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      os: osx
    - rvm: 2.6
      env: COVERAGE=BriefSummary,Coveralls
